language: node_js
node_js:
  - 11
branches:
  only:
    - master
    - development
    - "/^release\\/v\\d+\\.\\d+\\.\\d+(-(alpha|beta).*)?$/"
install:
  - npm run install-all
script:
  - npm run format-ci
  - npm run lint
  - npm run test-ci
after_success:
  - npm run coverage-report-client
deploy:
  provider: heroku
  api_key:
    secure: ITqI8r9O1ziyWdXcHwocu6iQuI9W7vWLTlfeAfh2pyeydukw7f3OZdtEd2HBHtMr4mkM6rjgWnB4D16TwL7BsYVMfPR9JeKRFe2jW+wIaymLXzIxaZQrXKswnl52KL/bH8YUelCvO1b791uCReeduPjQTlq+ryuv65b3TesJbZh+NjueYAVAztX+vIl7Aa9mZsPRUin5X66Sl8dvwjiT6kmf4ZLZhNLfOW/45pRMaeaTniCa0xQQd+ld5CwninzU5WkyArDljK4zojMxUyYbICr3GpJMr64oo+aB3DNI+czGmujuDlAHTO1tZpXWpTd+TJsMQGXErFlBIoaEpRGRn4TILdZrkWXourOsVjcKtMX8z2rBRl5m3F03eHHr72bieAHUlmJQ6LScTBl3mM/H3coTsln9azDuMZ3ETTRxmmj+ofh4/FH49RwsSW4nUePGnx/2jCNKobQYl3L8tUMNp4CmMK3S8UVfYoUyhQhiwgYHj/UjLUIlCialjiAZL7YNGf40SSwNu91Kf91xCOvP1lAujYYiIfesLU9MI6QUcoNqRZhB3mfYt8QyXXi+kTlhjk0DH0JAbOy4u02CRTkGgqpyaJWEsESUJdFhUutKXaLZP9nHQueFd/Nqfq7iqQx4kSNCffRNQ9u/q8W6sGmEj4CsDQ+h4E98Ci2ADxMnta4=
  app: supernintendogameinfo
  on:
    repo: ianrosedev/Super-Nintendo-Game-Info
